name: CD - Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - backend/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: store
        ports:
          - "3307:3306"
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: build version number
        run: echo "TIMESTAMP=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Update dockerrun.aws.json
        run: |
          sed -i "s|\"image\": \"loganjia/store:latest\"|\"image\": \"loganjia/store:${{ env.TIMESTAMP }}\"|g" dockerrun.aws.json
          cat dockerrun.aws.json

      - name: Deploy with Maven
        run: |
          mvn -ntp -B verify \
          -Ddocker.image.version="${{ env.TIMESTAMP }}" jib:build

      - name: Deploy to AWS EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ vars.EB_APPLICATION_NAME }}
          environment_name: ${{ vars.EB_ENVIRONMENT_NAME }}
          version_label: ${{ env.TIMESTAMP }}
          version_description: ${{github.SHA}}
          region: ${{ vars.EB_REGION }}
          deployment_package: backend/dockerrun.aws.json

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Update dockerrun.aws.json tag to ${{ env.TIMESTAMP }}"
          git push