name: CI - Build Backend

on:
  pull_request:
    branches:
      - master
    paths:
      - backend/**
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: store
        ports:
          - "3307:3306"
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and run unit/integration tests with Maven
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.github_actions.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.github_actions.DOCKER_HUB_TOKEN }}
          VARNAME1: ${{ env.VARNAME1 }}
          VARNAME2: ${{ env.github_actions.VARNAME1 }}
          VARNAME3: ${{ secrets.github_actions.DOCKER_HUB_USERNAME }}
        run: |
          mvn -ntp -B verify \
            -Djib.to.auth.username=$DOCKER_HUB_USERNAME \
            -Djib.to.auth.password=$DOCKER_HUB_TOKEN