name: CI - Build Backend

on:
  pull_request:
    branches:
      - master
    paths:
      - backend/**
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: store
        ports:
          - "3306:3307"
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and run unit/integration tests with Maven
        run: mvn -ntp -B verify